[versions]
agp = "8.13.1"
kotlin = "2.2.21"
ksp = "2.3.2"
# Sesl: https://github.com/tribalfs/sesl-androidx/tree/sesl-androidx-main
appcompat = "1.7.1+1.0.21-sesl8+rev2"
material = "1.12.0+1.0.32-sesl8+rev1"
# AndroidX: https://developer.android.com/jetpack/androidx/versions
annotation = "1.9.1"
window = "1.5.0"
# Xposed: https://github.com/rovo89/XposedBridge
xposed = "82"
# YukiHookAPI: https://github.com/HighCapable/YukiHookAPI
yukihookapi = "1.3.1"
# KavaRef: https://github.com/HighCapable/KavaRef
kavaref-core = "1.0.2"
kavaref-extension = "1.0.1"
# AndroidHiddenApiBypass: https://github.com/LSPosed/AndroidHiddenApiBypass
hiddenapibypass = "6.1"
# HiddenApiRefinePlugin: https://github.com/RikkaApps/HiddenApiRefinePlugin
refine = "4.4.0"

[libraries]
sesl-appcompat = { group = "sesl.androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
sesl-material = { group = "sesl.com.google.android.material", name = "material", version.ref = "material" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }
yukihookapi-api = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukihookapi" }
yukihookapi-ksp = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version.ref = "yukihookapi" }
kavaref-core = { group = "com.highcapable.kavaref", name = "kavaref-core", version.ref = "kavaref-core" }
kavaref-extension = { group = "com.highcapable.kavaref", name = "kavaref-extension", version.ref = "kavaref-extension" }
lsposed-hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapibypass" }
rikka-refine-annotationprocessor = { group = "dev.rikka.tools.refine", name = "annotation-processor", version.ref = "refine" }
rikka-refine-annotation = { group = "dev.rikka.tools.refine", name = "annotation", version.ref = "refine" }
rikka-refine-runtime = { group = "dev.rikka.tools.refine", name = "runtime", version.ref = "refine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
rikka-refine = { id = "dev.rikka.tools.refine", version.ref = "refine" }
